#!/usr/bin/env bash
# deploy.sh — Push the latest briefing to GitHub Pages
#
# Usage:
#   cd /path/to/stock-briefing-repo
#   bash deploy.sh
#
# Prerequisites:
#   - Git repo initialized with a remote named 'origin'
#   - GitHub Pages enabled on the 'main' branch (root /)
#   - gh CLI authenticated OR SSH key configured
#
# The script expects site/index.html to exist (generated by the skill).

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
SITE_DIR="${REPO_DIR}/site"
DATE=$(date +%Y-%m-%d)

cd "$REPO_DIR"

# Verify index.html exists
if [[ ! -f "${SITE_DIR}/index.html" ]]; then
  echo "ERROR: site/index.html not found. Run the briefing skill first."
  exit 1
fi

# Stage changes
git add site/

# Check if there are changes to commit
if git diff --cached --quiet; then
  echo "No changes to deploy."
  exit 0
fi

# Commit and push
git commit -m "Briefing update: ${DATE}"
git push origin main

echo "Deployed briefing for ${DATE} to GitHub Pages."
echo "URL: https://$(git remote get-url origin | sed -E 's|.*github\.com[:/]([^/]+)/([^/.]+).*|\1.github.io/\2|')/index.html"
